# Generated by Django 5.0.7 on 2024-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmploeeName', models.CharField(max_length=300)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoing', models.DateTimeField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
